name: Maven Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    permissions:
      contents: write
      packages: write
      actions: write
      repository-projects: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: mvn-repo
          settings-path: ${{ github.workspace }}

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Switch to SSH
        run: git remote set-url origin git@github.com:${{ github.repository }}.git

      - name: Build with Maven
        run: mvn -P exec-jar clean install

      - name: Maven Release
        run: |
          git config user.name "deripas"
          git config user.email "deripas@yandex.ru"
          mvn release:prepare --batch-mode 
          mvn release:perform -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}