package org.deripas.chrome.protocol.api.network;

import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import jdk.jfr.Experimental;
import lombok.Builder;
import lombok.Data;
import lombok.Generated;

/**
 * An object representing a report generated by the Reporting API.
 */
@Data
@Builder(
    toBuilder = true
)
@Experimental
@Generated
public class ReportingApiReport {
  private final ReportId id;

  /**
   * The URL of the document that triggered the report.
   */
  private final String initiatorUrl;

  /**
   * The name of the endpoint group that should be used to deliver the report.
   */
  private final String destination;

  /**
   * The type of the report (specifies the set of data that is contained in the report body).
   */
  private final String type;

  /**
   * When the report was generated.
   */
  private final TimeSinceEpoch timestamp;

  /**
   * How many uploads deep the related request was.
   */
  private final Integer depth;

  /**
   * The number of delivery attempts made so far, not including an active attempt.
   */
  private final Integer completedAttempts;

  private final Map body;

  private final ReportStatus status;
}
